export enum QuerieKeys {
  SignupWithEmailAndPassword = 'SIGNUP_WITH_EMAIL_AND_PASSWORD',
  SigninWithEmailAndPassword = 'SIGNIN_WITH_EMAIL_AND_PASSWORD',
  GetRankingsByUser = 'GET_RANKINGS_BY_USER',
  CreateRanking = 'CREATE_RANKING',
  CreateRankingItem = 'CREATE_RANKING_ITEM',
  UploadFile = 'UPLOAD_FILE',
  UpdateRanking = 'UPDATE_RANKING',
  UpdateRankingItem = 'UPDATE_RANKING_ITEM',
  GetRankingCriteriaSuggest = 'GET_RANKING_CRITERIA_SUGGEST',
  CreateRankingCriteria = 'CREATE_RANKING_CRITERIA',
  RemoveRankingCriteria = 'REMOVE_RANKING_CRITERIA',
  GetRankingItems = 'GET_RANKING_ITEMS',
  GetRankingItemsScores = 'GET_RANKING_ITEMS_SCORES',
  GetRankingCriteria = 'GET_RANKING_CRITERIA',
  InviteUserToRanking = 'INVITE_USER_TO_RANKING',
  UpdateUserPushToken = 'UPDATE_USER_PUSH_TOKEN',
}